name: 'DataTrails SCITT API'
description: 'Register, Get Receipts and Query Feeds from the DataTrails SCITT API'
inputs:
  datatrails-client_id:
    description: 'The CLIENT_ID used to access the DataTrails SCITT APIs'
    required: true
  datatrails-secret:
    description: 'The SECRET used to access the DataTrails SCITT APIs'
    required: true
  subject:
    description: 'Unique ID for the collection of statements about an artifact'
    required: true
  payload:
    description: 'The payload file to be registered on the SCITT Service (eg: SBOM, Scan Result, Attestation)'
    required: true
  content-type:
    description: 'The payload content type (iana mediaType) to be registered on the SCITT Service (eg: application/spdx+json, application/vnd.cyclonedx+json, Scan Result, Attestation)'
    required: true
  signed-statement-file:
    description: 'File representing the signed SCITT Statement that will be registered on SCITT.'
    required: false
    default: 'signed-statement.cbor'
  receipt-file:
    description: 'The file to save the cbor receipt'
    required: false
    default: 'receipt.cbor'
outputs:
  token: # id of output
    description: 'the token used to authenticate'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.datatrails-client_id }}
    - ${{ inputs.datatrails-secret }}
    - ${{ inputs.subject }}
    - ${{ inputs.payload }}
    - ${{ inputs.content-type }}
    - ${{ inputs.signed-statement-file }}
    - ${{ inputs.receipt-file }}
